name: ai-gone-astray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pytorch-lightning=1.0.2
  - GitPython=3.1.12
  - pandas=1.3.4
  - scikit-learn=0.24.2
  - pyarrow=5.0.0
  - cudatoolkit=11.1
  - pytorch=1.10.1
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - pip=20.2.2
  - pip:
    - comet-ml==3.2.10

